# Generated by Django 4.2.2 on 2023-09-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='color',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
