# Generated by Django 4.2.2 on 2023-09-06 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razor_payment_id', models.CharField(max_length=255)),
                ('amount_paid', models.CharField(max_length=100)),
                ('razor_pay_status', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PaymentCar',
        ),
        migrations.AddField(
            model_name='bookingcar',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Booking.bookingcar'),
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
