# Generated by Django 4.2.2 on 2023-09-06 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel_income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_bookings', models.IntegerField()),
                ('total_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('pending_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.vehicle')),
            ],
        ),
    ]
