# Generated by Django 4.2.2 on 2023-09-06 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
        ('Admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hotel_income',
            new_name='car_income',
        ),
    ]
