# Generated by Django 4.2.2 on 2023-09-09 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_panel', '0002_rename_hotel_income_car_income'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car_income',
            old_name='hotel',
            new_name='cars',
        ),
    ]
